### ISSUE TITLE
OSError: [WinError 10049] The requested address is not valid in its context

### ISSUE THREAD

**Issue by g3gant** [JoelBender/bacpypes#318]
When I'm trying to run WhoIsIam.py I'm getting this error:
Traceback (most recent call last):
  File "WhoIsIAm.py", line 181, in <module>
    main()
  File "WhoIsIAm.py", line 165, in main
    this_application = WhoIsIAmApplication(this_device, args.ini.address)
  File "WhoIsIAm.py", line 41, in __init__
    BIPSimpleApplication.__init__(self, *args)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bacpypes\app.py", line 535, in __init__
    self.mux = UDPMultiplexer(self.localAddress)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bacpypes\bvllservice.py", line 96, in __init__
    self.directPort = UDPDirector(self.addrTuple)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bacpypes\udp.py", line 155, in __init__
    self.bind(address)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python38-32\lib\asyncore.py", line 326, in bind
    return self.socket.bind(addr)
OSError: [WinError 10049] The requested address is not valid in its context

**Comment by g3gant** [comment]
Sorry, my bad. I was using a wrong address.
