### ISSUE TITLE
Trouble routing from a modem to a server

### ISSUE THREAD

**Issue by Andersk87** [JoelBender/bacpypes#488]
Hi!

I'm strugling to get a BBMD route from a Teltonika modem running bacpypes to a server in Azure. We have a custom APN, with all bacnet-ports open.

I Have a device with the IP 172.22.108.7 On the modem. The modem have the adress: 172.24.1.54. The server have the adress 10.64.160.133.

I have tried the IP2IPRouter-example, with the following error:

`python IP2IPRouter.py 10.64.160.133/24:47808 1 172.22.180.7/24:47808 1
Traceback (most recent call last):
  File "/root/bacnet/IP2IPRouter.py", line 126, in <module>
    main()
  File "/root/bacnet/IP2IPRouter.py", line 112, in main
    router = IP2IPRouter(Address(args.addr1), args.net1, Address(args.addr2), args.net2)
  File "/root/bacnet/IP2IPRouter.py", line 55, in __init__
    self.s1_mux = UDPMultiplexer(addr1)
  File "/usr/lib/python3.9/site-packages/bacpypes/bvllservice.py", line 96, in __init__
    self.directPort = UDPDirector(self.addrTuple)
  File "/usr/lib/python3.9/site-packages/bacpypes/udp.py", line 155, in __init__
    self.bind(address)
  File "/usr/lib/python3.9/asyncore.py", line 326, in bind
OSError: [Errno 99] Address not available`

what am I missing here?

**Comment by JoelBender** [comment]
First, make sure you are using the correct network identifiers for the two link layers, so at least pick one of them as `1` and the other as `2`

```$ python IP2IPRouter.py 10.64.160.133/24:47808 1 172.22.180.7/24:47808 2```

Now double check that the IPv4 network size is correct, they might not both be `/24` networks.  The application will attempt to open sockets for **10.64.160.133** for unicast, **10.64.160.255** for broadcast, and **172.22.180.7** for unicast, **172.22.180.255** for broadcast.  At least one of those is failing.
